### PR TITLE
Replace static AMI IDs with search

### PR DESCRIPTION
**Pull request by tm23**

### CODE REVIEW

**Review by weslambert — CHANGES_REQUESTED** [review]
Great idea, and thanks for submitting a PR!  Could we also remark the SO AMI in `variables.tf`, and also remove it from `terraform.tfvars` to avoid confusion?  I think it would also be great if we could override the latest AMI if needed by adding it back to `terraform.tfvars`.

**Comment by tm23** [comment]
I've removed the AMIs from the default terraform.tfvars, and added in a conditional so if it can't find an AMI via search/filters, it will fallback to the variable.

**Review by weslambert — APPROVED** [review]
Excellent, thank you!

**Review by weslambert — CHANGES_REQUESTED** [review]
Sorry, but we just noticed these commits were not signed -- could you please sign the commits, or re-submit the PR with signed commits? 😃

**Comment by tm23** [comment]
Sure, brb

**Pull request closed without merging**
